/*
slug-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkRequest{}

// CreateLinkRequest struct for CreateLinkRequest
type CreateLinkRequest struct {
	Data CreateLinkRequestData `json:"data"`
}

type _CreateLinkRequest CreateLinkRequest

// NewCreateLinkRequest instantiates a new CreateLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkRequest(data CreateLinkRequestData) *CreateLinkRequest {
	this := CreateLinkRequest{}
	this.Data = data
	return &this
}

// NewCreateLinkRequestWithDefaults instantiates a new CreateLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkRequestWithDefaults() *CreateLinkRequest {
	this := CreateLinkRequest{}
	return &this
}

// GetData returns the Data field value
func (o *CreateLinkRequest) GetData() CreateLinkRequestData {
	if o == nil {
		var ret CreateLinkRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateLinkRequest) GetDataOk() (*CreateLinkRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateLinkRequest) SetData(v CreateLinkRequestData) {
	o.Data = v
}

func (o CreateLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateLinkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLinkRequest := _CreateLinkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLinkRequest)

	if err != nil {
		return err
	}

	*o = CreateLinkRequest(varCreateLinkRequest)

	return err
}

type NullableCreateLinkRequest struct {
	value *CreateLinkRequest
	isSet bool
}

func (v NullableCreateLinkRequest) Get() *CreateLinkRequest {
	return v.value
}

func (v *NullableCreateLinkRequest) Set(val *CreateLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkRequest(val *CreateLinkRequest) *NullableCreateLinkRequest {
	return &NullableCreateLinkRequest{value: val, isSet: true}
}

func (v NullableCreateLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
