/*
slug-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the CreateLinkRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkRequestDataAttributes{}

// CreateLinkRequestDataAttributes struct for CreateLinkRequestDataAttributes
type CreateLinkRequestDataAttributes struct {
	TargetUrl *string       `json:"target_url,omitempty"`
	Slug      *string       `json:"slug,omitempty"`
	Ttl       NullableInt64 `json:"ttl,omitempty"`
}

// NewCreateLinkRequestDataAttributes instantiates a new CreateLinkRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkRequestDataAttributes() *CreateLinkRequestDataAttributes {
	this := CreateLinkRequestDataAttributes{}
	return &this
}

// NewCreateLinkRequestDataAttributesWithDefaults instantiates a new CreateLinkRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkRequestDataAttributesWithDefaults() *CreateLinkRequestDataAttributes {
	this := CreateLinkRequestDataAttributes{}
	return &this
}

// GetTargetUrl returns the TargetUrl field value if set, zero value otherwise.
func (o *CreateLinkRequestDataAttributes) GetTargetUrl() string {
	if o == nil || IsNil(o.TargetUrl) {
		var ret string
		return ret
	}
	return *o.TargetUrl
}

// GetTargetUrlOk returns a tuple with the TargetUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequestDataAttributes) GetTargetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TargetUrl) {
		return nil, false
	}
	return o.TargetUrl, true
}

// HasTargetUrl returns a boolean if a field has been set.
func (o *CreateLinkRequestDataAttributes) HasTargetUrl() bool {
	if o != nil && !IsNil(o.TargetUrl) {
		return true
	}

	return false
}

// SetTargetUrl gets a reference to the given string and assigns it to the TargetUrl field.
func (o *CreateLinkRequestDataAttributes) SetTargetUrl(v string) {
	o.TargetUrl = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *CreateLinkRequestDataAttributes) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequestDataAttributes) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *CreateLinkRequestDataAttributes) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *CreateLinkRequestDataAttributes) SetSlug(v string) {
	o.Slug = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateLinkRequestDataAttributes) GetTtl() int64 {
	if o == nil || IsNil(o.Ttl.Get()) {
		var ret int64
		return ret
	}
	return *o.Ttl.Get()
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateLinkRequestDataAttributes) GetTtlOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ttl.Get(), o.Ttl.IsSet()
}

// HasTtl returns a boolean if a field has been set.
func (o *CreateLinkRequestDataAttributes) HasTtl() bool {
	if o != nil && o.Ttl.IsSet() {
		return true
	}

	return false
}

// SetTtl gets a reference to the given NullableInt64 and assigns it to the Ttl field.
func (o *CreateLinkRequestDataAttributes) SetTtl(v int64) {
	o.Ttl.Set(&v)
}

// SetTtlNil sets the value for Ttl to be an explicit nil
func (o *CreateLinkRequestDataAttributes) SetTtlNil() {
	o.Ttl.Set(nil)
}

// UnsetTtl ensures that no value is present for Ttl, not even an explicit nil
func (o *CreateLinkRequestDataAttributes) UnsetTtl() {
	o.Ttl.Unset()
}

func (o CreateLinkRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetUrl) {
		toSerialize["target_url"] = o.TargetUrl
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if o.Ttl.IsSet() {
		toSerialize["ttl"] = o.Ttl.Get()
	}
	return toSerialize, nil
}

type NullableCreateLinkRequestDataAttributes struct {
	value *CreateLinkRequestDataAttributes
	isSet bool
}

func (v NullableCreateLinkRequestDataAttributes) Get() *CreateLinkRequestDataAttributes {
	return v.value
}

func (v *NullableCreateLinkRequestDataAttributes) Set(val *CreateLinkRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkRequestDataAttributes(val *CreateLinkRequestDataAttributes) *NullableCreateLinkRequestDataAttributes {
	return &NullableCreateLinkRequestDataAttributes{value: val, isSet: true}
}

func (v NullableCreateLinkRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
