/*
slug-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateLinkRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLinkRequestData{}

// CreateLinkRequestData struct for CreateLinkRequestData
type CreateLinkRequestData struct {
	Type       string                          `json:"type"`
	Attributes CreateLinkRequestDataAttributes `json:"attributes"`
}

type _CreateLinkRequestData CreateLinkRequestData

// NewCreateLinkRequestData instantiates a new CreateLinkRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkRequestData(type_ string, attributes CreateLinkRequestDataAttributes) *CreateLinkRequestData {
	this := CreateLinkRequestData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateLinkRequestDataWithDefaults instantiates a new CreateLinkRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkRequestDataWithDefaults() *CreateLinkRequestData {
	this := CreateLinkRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateLinkRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateLinkRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateLinkRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateLinkRequestData) GetAttributes() CreateLinkRequestDataAttributes {
	if o == nil {
		var ret CreateLinkRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateLinkRequestData) GetAttributesOk() (*CreateLinkRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateLinkRequestData) SetAttributes(v CreateLinkRequestDataAttributes) {
	o.Attributes = v
}

func (o CreateLinkRequestData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLinkRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateLinkRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLinkRequestData := _CreateLinkRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateLinkRequestData)

	if err != nil {
		return err
	}

	*o = CreateLinkRequestData(varCreateLinkRequestData)

	return err
}

type NullableCreateLinkRequestData struct {
	value *CreateLinkRequestData
	isSet bool
}

func (v NullableCreateLinkRequestData) Get() *CreateLinkRequestData {
	return v.value
}

func (v *NullableCreateLinkRequestData) Set(val *CreateLinkRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkRequestData(val *CreateLinkRequestData) *NullableCreateLinkRequestData {
	return &NullableCreateLinkRequestData{value: val, isSet: true}
}

func (v NullableCreateLinkRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
