/*
slug-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LinkAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkAttributes{}

// LinkAttributes struct for LinkAttributes
type LinkAttributes struct {
	Slug      string `json:"slug"`
	TargetUrl string `json:"target_url"`
	// ISO 8601 date-time string
	CreatedAt *string       `json:"created_at,omitempty"`
	Ttl       NullableInt64 `json:"ttl,omitempty"`
}

type _LinkAttributes LinkAttributes

// NewLinkAttributes instantiates a new LinkAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkAttributes(slug string, targetUrl string) *LinkAttributes {
	this := LinkAttributes{}
	this.Slug = slug
	this.TargetUrl = targetUrl
	return &this
}

// NewLinkAttributesWithDefaults instantiates a new LinkAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkAttributesWithDefaults() *LinkAttributes {
	this := LinkAttributes{}
	return &this
}

// GetSlug returns the Slug field value
func (o *LinkAttributes) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *LinkAttributes) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *LinkAttributes) SetSlug(v string) {
	o.Slug = v
}

// GetTargetUrl returns the TargetUrl field value
func (o *LinkAttributes) GetTargetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetUrl
}

// GetTargetUrlOk returns a tuple with the TargetUrl field value
// and a boolean to check if the value has been set.
func (o *LinkAttributes) GetTargetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetUrl, true
}

// SetTargetUrl sets field value
func (o *LinkAttributes) SetTargetUrl(v string) {
	o.TargetUrl = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *LinkAttributes) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkAttributes) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *LinkAttributes) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *LinkAttributes) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LinkAttributes) GetTtl() int64 {
	if o == nil || IsNil(o.Ttl.Get()) {
		var ret int64
		return ret
	}
	return *o.Ttl.Get()
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LinkAttributes) GetTtlOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ttl.Get(), o.Ttl.IsSet()
}

// HasTtl returns a boolean if a field has been set.
func (o *LinkAttributes) HasTtl() bool {
	if o != nil && o.Ttl.IsSet() {
		return true
	}

	return false
}

// SetTtl gets a reference to the given NullableInt64 and assigns it to the Ttl field.
func (o *LinkAttributes) SetTtl(v int64) {
	o.Ttl.Set(&v)
}

// SetTtlNil sets the value for Ttl to be an explicit nil
func (o *LinkAttributes) SetTtlNil() {
	o.Ttl.Set(nil)
}

// UnsetTtl ensures that no value is present for Ttl, not even an explicit nil
func (o *LinkAttributes) UnsetTtl() {
	o.Ttl.Unset()
}

func (o LinkAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["target_url"] = o.TargetUrl
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Ttl.IsSet() {
		toSerialize["ttl"] = o.Ttl.Get()
	}
	return toSerialize, nil
}

func (o *LinkAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"target_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkAttributes := _LinkAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkAttributes)

	if err != nil {
		return err
	}

	*o = LinkAttributes(varLinkAttributes)

	return err
}

type NullableLinkAttributes struct {
	value *LinkAttributes
	isSet bool
}

func (v NullableLinkAttributes) Get() *LinkAttributes {
	return v.value
}

func (v *NullableLinkAttributes) Set(val *LinkAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkAttributes(val *LinkAttributes) *NullableLinkAttributes {
	return &NullableLinkAttributes{value: val, isSet: true}
}

func (v NullableLinkAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
