/*
slug-svc

Testing LinksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package resources

import (
	"context"
	"testing"

	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_resources_LinksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LinksAPIService CreateLink", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LinksAPI.CreateLink(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinksAPIService ResolveLink", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var slug string

		resp, httpRes, err := apiClient.LinksAPI.ResolveLink(context.Background(), slug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
